'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import { FileText, FileDown, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { InterviewReport, InterviewSession, RoundEvaluation } from '@/types/interview';

interface ExportButtonsProps {
  report: InterviewReport;
  session: InterviewSession;
}

export function ExportButtons({ report, session }: ExportButtonsProps) {
  const t = useTranslations('interview.report');
  const [pdfLoading, setPdfLoading] = useState(false);

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const filePrefix = `interview-report-${session.jobTitle}-${new Date(session.createdAt).toISOString().slice(0, 10)}`;

  const exportMarkdown = () => {
    downloadFile(generateMarkdown(report, session), `${filePrefix}.md`, 'text/markdown');
  };

  const exportPdf = async () => {
    setPdfLoading(true);
    try {
      const fp = localStorage.getItem('jade_fingerprint');
      const res = await fetch(`/api/interview/${session.id}/report/export`, {
        headers: fp ? { 'x-fingerprint': fp } : {},
      });
      if (!res.ok) throw new Error('Failed to export PDF');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filePrefix}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={exportPdf} disabled={pdfLoading}>
        {pdfLoading ? <Loader2 className="mr-1 h-4 w-4 animate-spin" /> : <FileDown className="mr-1 h-4 w-4" />}
        {t('exportPdf')}
      </Button>
      <Button variant="outline" size="sm" onClick={exportMarkdown}>
        <FileText className="mr-1 h-4 w-4" />
        {t('exportMarkdown')}
      </Button>
    </div>
  );
}

function generateMarkdown(report: InterviewReport, session: InterviewSession): string {
  const lines: string[] = [];
  const rounds = report.roundEvaluations as RoundEvaluation[];

  lines.push(`# 面试报告：${session.jobTitle}`);
  lines.push(`> 日期：${new Date(session.createdAt).toLocaleDateString()} · 综合评分：${report.overallScore}/100\n`);
  lines.push(`## 总体评价\n\n${report.overallFeedback}\n`);

  lines.push(`## 能力维度\n`);
  for (const d of report.dimensionScores) {
    lines.push(`- **${d.dimension}**：${d.score}/100`);
  }
  lines.push('');

  lines.push(`## 分轮评估\n`);
  for (const r of rounds) {
    lines.push(`### ${r.interviewerName}（${r.interviewerType}）— ${r.score}/100\n`);
    lines.push(`${r.feedback}\n`);
    for (const q of r.questions) {
      const tags = [q.marked && '📌复习', q.hinted && '💡提示', q.skipped && '⏭跳过'].filter(Boolean).join(' ');
      lines.push(`#### Q: ${q.question} ${'⭐'.repeat(q.score)} ${tags}\n`);
      lines.push(`**回答摘要**：${q.answerSummary}\n`);
      if (q.highlights.length) lines.push(`✅ **亮点**：${q.highlights.join('；')}\n`);
      if (q.weaknesses.length) lines.push(`❌ **不足**：${q.weaknesses.join('；')}\n`);
      lines.push(`📖 **参考**：${q.referenceTips}\n`);
    }
  }

  lines.push(`## 改进建议\n`);
  for (const item of report.improvementPlan) {
    const label = { high: '🔴 高', medium: '🟡 中', low: '🟢 低' }[item.priority] || item.priority;
    lines.push(`### [${label}] ${item.area}\n`);
    lines.push(`${item.description}\n`);
    if (item.resources.length) lines.push(`> 推荐资源：${item.resources.join('；')}\n`);
  }

  lines.push(`\n---\n*Generated by 简鹿*`);
  return lines.join('\n');
}
